### ISSUE TITLE
Not working in 2017.2

### ISSUE THREAD

**Issue by cosmicdan** [cgamache/erroritem#2]
Installed in 2017.2, restarted IDEA, and I see no difference.

Do I need to enable something somewhere? If so, listing that on the plugin page would be nice.

**Comment by Vampire** [comment]
No, it just works.
Just installed in 2018.1.5.

**Comment by cosmicdan** [comment]
Indeed, it's working in my current environment (forgot I even had this
installed heh).

Thanks, can close this.
